# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6afa9b3020f274fb0f30c9b565c1e7c318dad02c3e49338ac7d5e9198f345487d64417d3dc71ebb315544c1ce53452a1f3bb412e444c7a44672b8ab6acc280e

test:
  secret_key_base: cca7e116ddd2378e127b50653bfb6dae37c76b84af329a67e99af8cf4742da0697d9cbce3948daa94628dceac3b9eda2d07e57b68837c42cad560e4393ed8463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
